deblob-2.6.27-libre1

diff --git a/deblob-main b/deblob-main
--- a/deblob-main
+++ b/deblob-main
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (C) 2008 Alexandre Oliva <lxoliva@fsfla.org>
+# Copyright (C) 2008, 2009 Alexandre Oliva <lxoliva@fsfla.org>
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -63,7 +63,7 @@ esac
 
 mver=$1 extra=$2 sver=$3
 kver=$mver$sver libre=libre$extra
-deblob= dir=`echo $0 | sed 's,/[^/]*$,,'`
+deblob= dir=`echo "$0" | sed 's,[^/]*$,,;s,^$,.,;s,/*$,,'`
 
 if test ! -f linux-$kver.tar.bz2; then
   echo linux-$kver.tar.bz2 does not exist >&2
@@ -110,6 +110,11 @@ fi
 
 if test -f linux-$kver-$libre.patch; then
   echo linux-$kver-$libre.patch already exists >&2
+  exit 1
+fi
+
+if test -f linux-$kver-$libre.log; then
+  echo linux-$kver-$libre.log already exists >&2
   exit 1
 fi
 
@@ -173,10 +178,15 @@ echo Copying linux-$kver to linux-$kver-$libre
 cp linux-$kver.tar linux-$kver-$libre.tar
 cp -lR linux-$kver/. linux-$kver-$libre
 
-echo Deblobbing within linux-$kver-$libre
-if (cd linux-$kver-$libre && /bin/sh ../$deblob $force); then
-  :
-else
+rm -f linux-$kver-$libre.log linux-$kver-$libre.log.tmp
+echo Deblobbing within linux-$kver-$libre, saving output to linux-$kver-$libre.log
+# We can't just pipe deblob into tee, for then we fail to detect 
+# error conditions.  Use file renaming to tell whether we succeeded.
+if (cd linux-$kver-$libre && /bin/sh ../$deblob $force) 2>&1; then
+  mv linux-$kver-$libre.log.tmp linux-$kver-$libre.log
+fi | tee linux-$kver-$libre.log.tmp
+if test ! -f linux-$kver-$libre.log; then
+  mv linux-$kver-$libre.log.tmp linux-$kver-$libre.log
   echo $deblob failed, aborting >&2
   exit 1
 fi
